swagger: '2.0'
info:
  description: "Documentação da API do projeto. Para editar esse arquivo é recomendado utilizar a extensão do VSCode 'Swagger Viewer'"
  version: '1.0.0'
  title: 'Controle de Estoque'
host: 'localhost:3333'
tags:
  - name: 'Produtos'
    description: 'Operações relacionadas aos produtos'
  - name: 'Estoque'
    description: 'Operações relacionadas ao estoque'
schemes:
  - 'https'
paths:
  /:
    get:
      tags:
        - 'Produtos'
      summary: 'Obtém todos os produtos do sistema'
      description: ''
      operationId: 'getProdutos'
      produces:
        - 'application/json'
      responses:
        '200':
          description: 'Deu tudo certo'
          schema:
            type: 'array'
            items:
              type: 'object'
              $ref: '#/definitions/ProdutoResponse'
        '500':
          description: 'Internal server error'
    post:
      tags:
        - 'Produtos'
      summary: 'Adiciona produto'
      description: 'Adiciona um novo produto ao sistema'
      operationId: 'addProduto'
      consumes:
        - 'formData'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          description: 'Dados do produto. Imagem é um arquivo'
          required: true
          schema:
            type: 'object'
            $ref: '#/definitions/Produto'
      responses:
        '200':
          description: 'Deu tudo certo'
          schema:
            type: 'object'
            $ref: '#/definitions/ProdutoResponse'
        '400':
          description: 'Erros variados, mas com o padrão: <br/>{ erro: "Nenhuma imagem foi enviada" }'
        '500':
          description: 'Internal server error'
  /{id}:
    get:
      tags:
        - 'Produtos'
      summary: 'Obtém um produto específico do sistema'
      description: ''
      operationId: 'getProduto'
      parameters:
        - in: 'path'
          name: id
          required: true
          type: 'string'
      produces:
        - 'application/json'
      responses:
        '200':
          description: 'Deu tudo certo'
          schema:
            type: 'object'
            $ref: '#/definitions/ProdutoResponse'
        '500':
          description: 'Internal server error'
    put:
      tags:
        - 'Produtos'
      summary: 'Edita produto'
      description: 'Edita um produto do sistema'
      operationId: 'editProduto'
      consumes:
        - 'formData'
      produces:
        - 'application/json'
      parameters:
        - in: 'path'
          name: id
          required: true
          type: 'string'
        - in: 'body'
          name: 'body'
          description: 'Dados do produto. Imagem é um arquivo'
          required: true
          schema:
            type: 'object'
            $ref: '#/definitions/Produto'
      responses:
        '200':
          description: 'Deu tudo certo'
          schema:
            type: 'object'
            $ref: '#/definitions/ProdutoResponse'
        '400':
          description: 'Erros variados, mas com o padrão: <br/>{ erro: "Nenhuma imagem foi enviada" }'
        '404':
          description: '{ erro: "Objeto não encontrado" }'
        '500':
          description: 'Internal server error'
    delete:
      tags:
        - 'Produtos'
      summary: 'Deleta a instância de um produto'
      description: ''
      operationId: 'deleteProduto'
      produces:
        - 'application/json'
      parameters:
        - in: 'path'
          name: id
          required: true
          type: 'string'
      responses:
        '200':
          description: 'Deu tudo certo'
          schema:
            type: 'object'
            $ref: '#/definitions/ProdutoResponse'
        '400':
          description: 'Erros variados, mas com o padrão: <br/>{ erro: "ID inválido" }'
        '404':
          description: '{ erro: "Objeto não encontrado" }'
        '500':
          description: '{ erro: "Erro interno do servidor" }'
  /estoque/{id}:
    put:
      tags:
        - 'Estoque'
      summary: 'Edita estoque'
      description: 'Atualiza estoque do sistema'
      operationId: 'editEstoque'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'path'
          name: id
          required: true
          type: 'string'
          description: 'Id do produto que terá o estoque alterado'
        - in: 'body'
          name: 'body'
          description: 'Novo valor de estoque'
          required: true
          schema:
            type: 'object'
            properties:
              estoque:
                type: 'number'
                example: 100
      responses:
        '200':
          description: 'Deu tudo certo'
          schema:
            type: 'object'
            $ref: '#/definitions/ProdutoResponse'
        '400':
          description: 'Erros variados, mas com o padrão: <br/>{ erro: "Nenhuma imagem foi enviada" }'
        '404':
          description: '{ erro: "Objeto não encontrado" }'
        '500':
          description: 'Internal server error'

definitions:
  Produto:
    type: 'object'
    properties:
      nome:
        type: 'string'
        example: 'Produto 1'
      descricao:
        type: 'string'
        example: 'Descrição do produto 1'
      estoque:
        type: 'number'
        example: 100
      imagem:
        type: 'string'
        example: 'http://localhost:3333/uploads/images/{nome-da-imagem.extensao}'
  ProdutoResponse:
    type: 'object'
    properties:
      _id:
        type: 'string'
      nome:
        type: 'string'
        example: 'Produto 1'
      descricao:
        type: 'string'
        example: 'Descrição do produto 1'
      estoque:
        type: 'number'
        example: 100
      imagem:
        type: 'string'
        example: 'http://localhost:3333/uploads/images/{nome-da-imagem.extensao}'

externalDocs:
  description: 'Find out more about Swagger'
  url: 'http://swagger.io'
